# Generated by Django 5.2.7 on 2025-11-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='average_time_per_patient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='waiting_time_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
